name: crypto_app
description: "App to browse the top cryptocurrencies by market cap"
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_gen: 5.10.0
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  http: 1.3.0
  injectable: 2.5.0
  json_annotation: 4.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 5.0.0
  build_runner: 2.4.15
  flutter_gen_runner: 5.10.0
  injectable_generator: 2.7.0
  json_serializable: 6.9.4
  freezed: ^3.0.6

flutter:
  uses-material-design: true
  assets:
    - assets/


flutter_gen:
  output: lib/shared/gen
  line_length: 120